Repository sb01-deokhugam-team1/sb01-deokhugam-team1, pull requests merged in 2025-05, with the labels that each got.

#139 🔧 도서 서비스 조회 테스트 코드 작성
  src/test/java/com/codeit/duckhu/domain/book/repository/BookRepositoryImplTest.java
  src/test/java/com/codeit/duckhu/domain/book/repository/BookRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/book/repository/BookReviewTest.java
  src/test/java/com/codeit/duckhu/domain/book/repository/CustomRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/book/repository/PopularBookRepositoryImplTest.java
  src/test/java/com/codeit/duckhu/domain/book/service/BookServiceImplTest.java
  src/test/resources/books.sql
Labels: 👨🏻‍🏫테스트

#148 Ref/141 리뷰 테스트 코드 추가
  src/main/java/com/codeit/duckhu/domain/review/batch/PopularReviewItemProcessor.java
  src/main/java/com/codeit/duckhu/domain/review/batch/PopularReviewItemReader.java
  src/main/java/com/codeit/duckhu/domain/review/batch/PopularReviewItemWriter.java
  src/main/java/com/codeit/duckhu/domain/review/batch/PopularReviewJobConfig.java
  src/main/java/com/codeit/duckhu/domain/review/batch/PopularReviewStepConfig.java
  src/main/java/com/codeit/duckhu/domain/review/batch/RankUpdateItemProcessor.java
  src/main/java/com/codeit/duckhu/domain/review/batch/RankUpdateItemReader.java
  src/main/java/com/codeit/duckhu/domain/review/batch/RankUpdateItemWriter.java
  src/main/java/com/codeit/duckhu/domain/review/service/impl/PopularReviewBatchService.java
  src/test/java/com/codeit/duckhu/domain/review/batch/PopularReviewBatchIntegrationTest.java
  src/test/java/com/codeit/duckhu/domain/review/batch/PopularReviewItemProcessorTest.java
  src/test/java/com/codeit/duckhu/domain/review/batch/PopularReviewItemWriterTest.java
  src/test/java/com/codeit/duckhu/domain/review/batch/PopularReviewStepConfigTest.java
  src/test/java/com/codeit/duckhu/domain/review/repository/PopularReviewRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/review/repository/ReviewRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/review/service/ReviewServiceTest.java
Labels: 👨🏻‍🏫테스트

#151 [🛠Refactor] Node-Exporter 추가
  docker-compose-prod.yml
  docker-compose.yml
  monitoring/prometheus.yml
Labels: 🐉 성능

#153 :recycle: Naver API, OCR 에러 코드 상세 적용
  src/main/java/com/codeit/duckhu/domain/book/exception/NaverAPIException.java
  src/main/java/com/codeit/duckhu/domain/book/naver/ImageConverterImpl.java
  src/main/java/com/codeit/duckhu/domain/book/naver/NaverBookClient.java
  src/main/java/com/codeit/duckhu/domain/book/ocr/VisionOcrExtractor.java
  src/main/java/com/codeit/duckhu/domain/book/service/PopularBookBatchScheduler.java
  src/main/java/com/codeit/duckhu/domain/book/service/PopularBookBatchService.java
  src/main/java/com/codeit/duckhu/global/exception/ErrorCode.java
Labels: 🔨기능수리

#161 ♻️ 도서 서비스 로그 상세 추가
  src/main/java/com/codeit/duckhu/domain/book/controller/BookController.java
  src/main/java/com/codeit/duckhu/domain/book/exception/CustomS3Exception.java
  src/main/java/com/codeit/duckhu/domain/book/service/BookServiceImpl.java
  src/main/java/com/codeit/duckhu/domain/book/storage/s3/S3ThumbnailImageStorage.java
  src/main/java/com/codeit/duckhu/global/exception/ErrorCode.java
Labels: 🛠리팩토링

#162 Ref/158 리뷰 로그 추가 및 수정
  src/main/java/com/codeit/duckhu/domain/review/controller/ReviewController.java
  src/main/java/com/codeit/duckhu/domain/review/service/impl/PopularReviewBatchService.java
  src/main/java/com/codeit/duckhu/domain/review/service/impl/ReviewServiceImpl.java
  src/main/java/com/codeit/duckhu/global/exception/ErrorCode.java
Labels: 🛠리팩토링

#167 Docker 컨테이너에서 시간대 설정 누락으로 인한 9시간 오차 문제 해결
  Dockerfile
Labels: 🔨기능수리

#163 chore/149 Review Swagger Api 작성
  src/main/java/com/codeit/duckhu/domain/review/controller/api/ReviewApi.java
Labels: 📝문서

#168 [🛠Refactor] Loki적용으로 그라파나에서 로그 확인
  .gitignore
  docker-compose.yml
  monitoring/loki-config.yml
  monitoring/promtail-config.yml
Labels: 🐉 성능

#174 [🛠Refactor] 사용자 로그작업 & 사용자 서비스 테스트 커버리지 80%넘기기
  .gitignore
  src/main/java/com/codeit/duckhu/domain/user/controller/UserController.java
  src/main/java/com/codeit/duckhu/domain/user/service/PowerUserBatchScheduler.java
  src/main/java/com/codeit/duckhu/domain/user/service/UserServiceImpl.java
  src/test/java/com/codeit/duckhu/domain/user/controller/UserControllerTest.java
  src/test/java/com/codeit/duckhu/domain/user/service/UserServiceImplTest.java
  src/test/resources/application-test.yml
Labels: 🛠리팩토링, 👨🏻‍🏫테스트

#182 ♻️ OCR 통합 테스트 수정
  src/main/java/com/codeit/duckhu/domain/book/ocr/VisionOcrExtractor.java
  src/test/java/com/codeit/duckhu/domain/book/ocr/TesseractOcrExtractorIntegrationTest.java
  src/test/java/com/codeit/duckhu/domain/book/ocr/VisionOcrExtractorIntegrationTest.java
  src/test/java/com/codeit/duckhu/domain/book/ocr/VisionOcrExtractorTest.java
  src/test/resources/image_with_isbn.jpg
Labels: 🛠리팩토링, 👨🏻‍🏫테스트

#184 [Refactor] Spring Batch 리팩토링 및 테스트 코드
  src/main/java/com/codeit/duckhu/domain/review/batch/PopularReviewItemProcessor.java
  src/main/java/com/codeit/duckhu/domain/review/batch/PopularReviewItemReader.java
  src/main/java/com/codeit/duckhu/domain/review/batch/PopularReviewItemWriter.java
  src/main/java/com/codeit/duckhu/domain/review/batch/PopularReviewJobConfig.java
  src/main/java/com/codeit/duckhu/domain/review/batch/PopularReviewScheduledRunner.java
  src/main/java/com/codeit/duckhu/domain/review/batch/PopularReviewStepConfig.java
  src/main/java/com/codeit/duckhu/domain/review/batch/RankUpdateItemProcessor.java
  src/main/java/com/codeit/duckhu/domain/review/batch/RankUpdateItemReader.java
  src/main/java/com/codeit/duckhu/domain/review/batch/RankUpdateItemWriter.java
  src/main/java/com/codeit/duckhu/domain/review/batch/StepTimingListener.java
  src/main/java/com/codeit/duckhu/domain/review/repository/custom/impl/PopularReviewRepositoryCustomImpl.java
  src/main/java/com/codeit/duckhu/domain/review/service/impl/PopularReviewBatchService.java
  src/main/java/com/codeit/duckhu/domain/review/service/impl/ReviewServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/codeit/duckhu/domain/review/batch/PopularReviewBatchIntegrationTest.java
  src/test/java/com/codeit/duckhu/domain/review/batch/PopularReviewBatchUnitTest.java
  src/test/java/com/codeit/duckhu/domain/review/batch/PopularReviewItemProcessorTest.java
  src/test/java/com/codeit/duckhu/domain/review/batch/PopularReviewItemWriterTest.java
  src/test/java/com/codeit/duckhu/domain/review/batch/PopularReviewStepConfigTest.java
  src/test/java/com/codeit/duckhu/domain/review/repository/PopularReviewRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/review/repository/ReviewRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/review/service/ReviewServiceTest.java
Labels: 🛠리팩토링, 👨🏻‍🏫테스트

#187 [🛠Refactor] 파워유저 수정
  src/main/java/com/codeit/duckhu/domain/user/repository/poweruser/PowerUserRepositoryImpl.java
  src/main/java/com/codeit/duckhu/domain/user/service/UserServiceImpl.java
  src/test/java/com/codeit/duckhu/domain/user/repository/PowerUserRepositoryTest.java
Labels: 🐛버그
