Repository sb01-deokhugam-team1/sb01-deokhugam-team1, pull requests merged in 2025-04, with the labels that each got.

#7 ✨ feat: 도서, 인기 도서 엔티티 생성
  .gitattributes
  .github/ISSUE_TEMPLATE/♻️Refactor.yml
  .github/ISSUE_TEMPLATE/✨feature.yml
  .github/ISSUE_TEMPLATE/🐞bug.yml
  .github/ISSUE_TEMPLATE/🔧chore.yml
  .github/ISSUE_TEMPLATE/🚀deploy.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .gitmessage.txt
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  intellij-java-google-style.xml
  schema.sql
  settings.gradle
  src/main/java/com/codeit/duckhu/DuckhuApplication.java
  src/main/java/com/codeit/duckhu/domain/book/entity/Book.java
  src/main/java/com/codeit/duckhu/domain/book/entity/PopularBook.java
  src/main/java/com/codeit/duckhu/domain/book/repository/BookRepository.java
  src/main/java/com/codeit/duckhu/domain/book/repository/PopularBookRepository.java
  src/main/java/com/codeit/duckhu/global/config/AuditingConfig.java
  src/main/java/com/codeit/duckhu/global/entity/BaseEntity.java
  src/main/java/com/codeit/duckhu/global/entity/BaseUpdatableEntity.java
  src/main/java/com/codeit/duckhu/global/exception/CustomException.java
  src/main/java/com/codeit/duckhu/global/exception/ErrorCode.java
  src/main/java/com/codeit/duckhu/global/exception/GlobalExceptionHandler.java
  src/main/java/com/codeit/duckhu/global/response/CustomApiResponse.java
  src/main/java/com/codeit/duckhu/global/response/ErrorResponse.java
  src/main/java/com/codeit/duckhu/global/type/PeriodType.java
  src/main/resources/application.yml
  src/main/resources/static/assets/index-CngKKUej.js
  src/main/resources/static/assets/index-D30UMZL2.css
  src/main/resources/static/favicon-32x32.png
  src/main/resources/static/index.html
  src/main/resources/static/static/images/book-placeholder.png
  src/test/java/com/codeit/duckhu/DuckhuApplicationTests.java
  src/test/java/com/codeit/duckhu/domain/book/repository/BookRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/book/repository/PopularBookRepositoryTest.java
Labels: ✨기능, 👨🏻‍🏫테스트

#12 [✨Feat] 사용자 회원가입 기능 최초 구축
  .gitignore
  build.gradle
  src/main/java/com/codeit/duckhu/config/SwaggerConfig.java
  src/main/java/com/codeit/duckhu/domain/user/controller/UserController.java
  src/main/java/com/codeit/duckhu/domain/user/controller/api/UserApi.java
  src/main/java/com/codeit/duckhu/domain/user/dto/UserDto.java
  src/main/java/com/codeit/duckhu/domain/user/dto/UserRegisterRequest.java
  src/main/java/com/codeit/duckhu/domain/user/entity/User.java
  src/main/java/com/codeit/duckhu/domain/user/exception/EmailDuplicateException.java
  src/main/java/com/codeit/duckhu/domain/user/exception/UserErrorCode.java
  src/main/java/com/codeit/duckhu/domain/user/exception/UserErrorResponse.java
  src/main/java/com/codeit/duckhu/domain/user/exception/UserException.java
  src/main/java/com/codeit/duckhu/domain/user/exception/UserExceptionHandler.java
  src/main/java/com/codeit/duckhu/domain/user/mapper/UserMapper.java
  src/main/java/com/codeit/duckhu/domain/user/repository/UserRepository.java
  src/main/java/com/codeit/duckhu/domain/user/service/UserService.java
  src/main/java/com/codeit/duckhu/domain/user/service/UserServiceImpl.java
  src/main/java/com/codeit/duckhu/global/entity/BaseEntity.java
  src/main/resources/schema.sql
  src/test/java/com/codeit/duckhu/domain/user/controller/UserControllerTest.java
  src/test/java/com/codeit/duckhu/domain/user/integration/UserTest.java
  src/test/java/com/codeit/duckhu/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/user/service/UserServiceImplTest.java
  src/test/resources/application-test.yml
Labels: ✨기능, 👨🏻‍🏫테스트

#8 feat:3 Review 엔티티 생성, 테스트 코드
  gradlew
  src/main/java/com/codeit/duckhu/review/dto/ReviewCreateRequest.java
  src/main/java/com/codeit/duckhu/review/dto/ReviewDto.java
  src/main/java/com/codeit/duckhu/review/entity/Review.java
  src/main/java/com/codeit/duckhu/review/mapper/ReviewMapper.java
  src/main/java/com/codeit/duckhu/review/repository/ReviewRepository.java
  src/main/java/com/codeit/duckhu/review/service/ReviewService.java
  src/main/java/com/codeit/duckhu/review/service/impl/ReviewServiceImpl.java
  src/test/java/com/codeit/duckhu/review/repository/ReviewRepositoryTest.java
  src/test/java/com/codeit/duckhu/review/service/ReviewServiceTest.java
Labels: ✨기능, 👨🏻‍🏫테스트

#18 [✨Feat] 로그인 기능 구축
  src/main/java/com/codeit/duckhu/comments/domain/Comment.java
  src/main/java/com/codeit/duckhu/config/JpaConfig.java
  src/main/java/com/codeit/duckhu/domain/user/controller/UserController.java
  src/main/java/com/codeit/duckhu/domain/user/controller/api/UserApi.java
  src/main/java/com/codeit/duckhu/domain/user/dto/UserLoginRequest.java
  src/main/java/com/codeit/duckhu/domain/user/entity/User.java
  src/main/java/com/codeit/duckhu/domain/user/exception/InvalidLoginException.java
  src/main/java/com/codeit/duckhu/domain/user/exception/UserErrorCode.java
  src/main/java/com/codeit/duckhu/domain/user/exception/UserExceptionHandler.java
  src/main/java/com/codeit/duckhu/domain/user/repository/UserRepository.java
  src/main/java/com/codeit/duckhu/domain/user/service/UserService.java
  src/main/java/com/codeit/duckhu/domain/user/service/UserServiceImpl.java
  src/main/java/com/codeit/duckhu/global/entity/BaseEntity.java
  src/test/java/com/codeit/duckhu/comments/CommentTest.java
  src/test/java/com/codeit/duckhu/domain/user/controller/UserControllerTest.java
  src/test/java/com/codeit/duckhu/domain/user/integration/UserTest.java
  src/test/java/com/codeit/duckhu/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/user/service/UserServiceImplTest.java
  src/test/java/com/codeit/duckhu/review/service/ReviewServiceTest.java
Labels: ✨기능, 👨🏻‍🏫테스트

#22 ✨ 도서 정보 조회 Naver API 연동, 도서 이미지 저장 S3 설정하기
  .gitignore
  build.gradle
  src/main/java/com/codeit/duckhu/config/S3Config.java
  src/main/java/com/codeit/duckhu/domain/book/controller/BookController.java
  src/main/java/com/codeit/duckhu/domain/book/dto/BookCreateRequest.java
  src/main/java/com/codeit/duckhu/domain/book/dto/BookDto.java
  src/main/java/com/codeit/duckhu/domain/book/dto/BookUpdateRequest.java
  src/main/java/com/codeit/duckhu/domain/book/dto/CursorPageResponseBookDto.java
  src/main/java/com/codeit/duckhu/domain/book/dto/CursorPageResponsePopularBookDto.java
  src/main/java/com/codeit/duckhu/domain/book/dto/NaverApiResponse.java
  src/main/java/com/codeit/duckhu/domain/book/dto/NaverBookDto.java
  src/main/java/com/codeit/duckhu/domain/book/dto/PopularBookDto.java
  src/main/java/com/codeit/duckhu/domain/book/mapper/BookMapper.java
  src/main/java/com/codeit/duckhu/domain/book/naver/NaverBookClient.java
  src/main/java/com/codeit/duckhu/domain/book/service/BookService.java
  src/main/java/com/codeit/duckhu/domain/book/service/BookServiceImpl.java
  src/main/java/com/codeit/duckhu/domain/book/storage/ThumbnailImageStorage.java
  src/main/java/com/codeit/duckhu/domain/book/storage/s3/S3ThumbnailImageStorage.java
  src/main/java/com/codeit/duckhu/domain/comment/domain/Comment.java
  src/main/java/com/codeit/duckhu/global/config/AuditingConfig.java
  src/main/resources/application.yml
  src/test/java/com/codeit/duckhu/comments/CommentTest.java
  src/test/java/com/codeit/duckhu/domain/book/controller/BookControllerTest.java
  src/test/java/com/codeit/duckhu/domain/book/mapper/BookMapperTest.java
  src/test/java/com/codeit/duckhu/domain/book/naver/NaverBookClientIntegrationTest.java
  src/test/java/com/codeit/duckhu/domain/book/naver/NaverBookClientTest.java
  src/test/java/com/codeit/duckhu/domain/book/repository/BookRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/book/repository/PopularBookRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/book/storage/S3ThumbnailImageStorageTest.java
  src/test/java/com/codeit/duckhu/domain/comments/CommentControllerTest.java
  src/test/java/com/codeit/duckhu/domain/review/repository/ReviewRepositoryTest.java
Labels: ✨기능, 👨🏻‍🏫테스트, 🟢 완료

#24 [✨Feat] 사용자 상세 조회 기능 구축
  src/main/java/com/codeit/duckhu/config/JpaConfig.java
  src/main/java/com/codeit/duckhu/domain/user/controller/UserController.java
  src/main/java/com/codeit/duckhu/domain/user/controller/api/UserApi.java
  src/main/java/com/codeit/duckhu/domain/user/dto/UserDto.java
  src/main/java/com/codeit/duckhu/domain/user/entity/User.java
  src/main/java/com/codeit/duckhu/domain/user/exception/NotFoundUserException.java
  src/main/java/com/codeit/duckhu/domain/user/exception/UserErrorCode.java
  src/main/java/com/codeit/duckhu/domain/user/exception/UserExceptionHandler.java
  src/main/java/com/codeit/duckhu/domain/user/service/UserService.java
  src/main/java/com/codeit/duckhu/domain/user/service/UserServiceImpl.java
  src/test/java/com/codeit/duckhu/domain/user/controller/UserControllerTest.java
  src/test/java/com/codeit/duckhu/domain/user/integration/UserTest.java
  src/test/java/com/codeit/duckhu/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/user/service/UserServiceImplTest.java
  src/test/resources/application-test.yml
  src/test/resources/data.sql
Labels: ✨기능, 👨🏻‍🏫테스트

#34 Feat/20 ReviewService, test에 User, Book 추가 및 리펙토링
  src/main/java/com/codeit/duckhu/domain/book/entity/Book.java
  src/main/java/com/codeit/duckhu/domain/comment/controller/CommentController.java
  src/main/java/com/codeit/duckhu/domain/comment/domain/Comment.java
  src/main/java/com/codeit/duckhu/domain/comment/repository/CommentRepository.java
  src/main/java/com/codeit/duckhu/domain/comment/service/CommentMapper.java
  src/main/java/com/codeit/duckhu/domain/comment/service/CommentService.java
  src/main/java/com/codeit/duckhu/domain/review/dto/ReviewCreateRequest.java
  src/main/java/com/codeit/duckhu/domain/review/dto/ReviewDto.java
  src/main/java/com/codeit/duckhu/domain/review/dto/ReviewUpdateRequest.java
  src/main/java/com/codeit/duckhu/domain/review/entity/Review.java
  src/main/java/com/codeit/duckhu/domain/review/exception/ReviewErrorCode.java
  src/main/java/com/codeit/duckhu/domain/review/mapper/ReviewMapper.java
  src/main/java/com/codeit/duckhu/domain/review/repository/ReviewRepository.java
  src/main/java/com/codeit/duckhu/domain/review/service/impl/ReviewServiceImpl.java
  src/main/java/com/codeit/duckhu/domain/user/dto/UserDto.java
  src/main/java/com/codeit/duckhu/domain/user/entity/User.java
  src/test/java/com/codeit/duckhu/domain/comments/CommentControllerTest.java
  src/test/java/com/codeit/duckhu/domain/comments/CommentServiceTest.java
  src/test/java/com/codeit/duckhu/domain/review/repository/ReviewRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/review/repository/TestJpaConfig.java
  src/test/java/com/codeit/duckhu/domain/review/service/ReviewServiceTest.java
Labels: 🛠리팩토링, 👨🏻‍🏫테스트

#32 ✨ 도서 등록 기능 구현하기
  src/main/java/com/codeit/duckhu/domain/book/controller/BookController.java
  src/main/java/com/codeit/duckhu/domain/book/dto/BookCreateRequest.java
  src/main/java/com/codeit/duckhu/domain/book/dto/CursorPageResponseBookDto.java
  src/main/java/com/codeit/duckhu/domain/book/dto/CursorPageResponsePopularBookDto.java
  src/main/java/com/codeit/duckhu/domain/book/exception/BookException.java
  src/main/java/com/codeit/duckhu/domain/book/exception/OCRException.java
  src/main/java/com/codeit/duckhu/domain/book/naver/NaverBookClient.java
  src/main/java/com/codeit/duckhu/domain/book/ocr/OcrExtractor.java
  src/main/java/com/codeit/duckhu/domain/book/ocr/VisionOcrExtractor.java
  src/main/java/com/codeit/duckhu/domain/book/repository/BookRepository.java
  src/main/java/com/codeit/duckhu/domain/book/service/BookServiceImpl.java
  src/main/java/com/codeit/duckhu/domain/book/storage/s3/S3ThumbnailImageStorage.java
  src/main/java/com/codeit/duckhu/global/exception/ErrorCode.java
  src/test/java/com/codeit/duckhu/domain/book/naver/NaverBookClientTest.java
  src/test/java/com/codeit/duckhu/domain/book/service/BookServiceImplTest.java
Labels: ✨기능, 👨🏻‍🏫테스트, 🟢 완료

#39 [✨Feat] 사용자 논리/물리삭제 기능 구축
  .gitignore
  src/main/java/com/codeit/duckhu/domain/user/controller/UserController.java
  src/main/java/com/codeit/duckhu/domain/user/controller/api/UserApi.java
  src/main/java/com/codeit/duckhu/domain/user/entity/User.java
  src/main/java/com/codeit/duckhu/domain/user/exception/ForbiddenDeleteException.java
  src/main/java/com/codeit/duckhu/domain/user/exception/UserErrorCode.java
  src/main/java/com/codeit/duckhu/domain/user/exception/UserExceptionHandler.java
  src/main/java/com/codeit/duckhu/domain/user/service/UserService.java
  src/main/java/com/codeit/duckhu/domain/user/service/UserServiceImpl.java
  src/test/java/com/codeit/duckhu/comments/CommentTest.java
  src/test/java/com/codeit/duckhu/domain/comments/CommentControllerTest.java
  src/test/java/com/codeit/duckhu/domain/user/controller/UserControllerTest.java
  src/test/java/com/codeit/duckhu/domain/user/integration/UserTest.java
  src/test/java/com/codeit/duckhu/domain/user/service/UserServiceImplTest.java
  src/test/resources/data.sql
Labels: ✨기능, 🐛버그, 👨🏻‍🏫테스트

#43 ✨ 도서 수정, 삭제 기능 구현
  src/main/java/com/codeit/duckhu/config/JpaConfig.java
  src/main/java/com/codeit/duckhu/domain/book/controller/BookController.java
  src/main/java/com/codeit/duckhu/domain/book/controller/api/BookApi.java
  src/main/java/com/codeit/duckhu/domain/book/entity/Book.java
  src/main/java/com/codeit/duckhu/domain/book/mapper/BookMapper.java
  src/main/java/com/codeit/duckhu/domain/book/service/BookService.java
  src/main/java/com/codeit/duckhu/domain/book/service/BookServiceImpl.java
  src/main/java/com/codeit/duckhu/domain/review/entity/Review.java
  src/main/java/com/codeit/duckhu/domain/review/repository/ReviewRepository.java
  src/test/java/com/codeit/duckhu/domain/book/controller/BookControllerTest.java
  src/test/java/com/codeit/duckhu/domain/book/naver/NaverBookClientTest.java
  src/test/java/com/codeit/duckhu/domain/book/repository/BookReviewTest.java
  src/test/java/com/codeit/duckhu/domain/book/service/BookServiceImplTest.java
  src/test/java/com/codeit/duckhu/domain/comments/CommentControllerTest.java
Labels: ✨기능, 👨🏻‍🏫테스트

#49 Feat/47 Review 물리적 삭제, 논리적 삭제 구현
  src/main/java/com/codeit/duckhu/domain/review/entity/Review.java
  src/main/java/com/codeit/duckhu/domain/review/service/ReviewService.java
  src/main/java/com/codeit/duckhu/domain/review/service/impl/ReviewServiceImpl.java
  src/test/java/com/codeit/duckhu/domain/comments/CommentControllerTest.java
  src/test/java/com/codeit/duckhu/domain/review/repository/ReviewRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/review/service/ReviewServiceTest.java
Labels: ✨기능, 👨🏻‍🏫테스트

#53 ✨ 도서 조회 기능 구현
  .gitignore
  schema.sql
  src/main/java/com/codeit/duckhu/domain/book/dto/CursorPageResponseBookDto.java
  src/main/java/com/codeit/duckhu/domain/book/entity/Book.java
  src/main/java/com/codeit/duckhu/domain/book/mapper/BookMapper.java
  src/main/java/com/codeit/duckhu/domain/book/naver/NaverBookClient.java
  src/main/java/com/codeit/duckhu/domain/book/repository/BookRepository.java
  src/main/java/com/codeit/duckhu/domain/book/repository/BookRepositoryCustom.java
  src/main/java/com/codeit/duckhu/domain/book/repository/BookRepositoryImpl.java
  src/main/java/com/codeit/duckhu/domain/book/service/BookServiceImpl.java
  src/main/java/com/codeit/duckhu/domain/book/storage/s3/S3ThumbnailImageStorage.java
  src/main/resources/application.yml
  src/test/java/com/codeit/duckhu/domain/book/repository/BookReviewTest.java
  src/test/java/com/codeit/duckhu/domain/book/repository/CustomRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/book/service/BookServiceImplTest.java
Labels: ✨기능, 👨🏻‍🏫테스트

#59 [🛠Refactor] 에러코드 관리
  src/main/java/com/codeit/duckhu/config/JpaConfig.java
  src/main/java/com/codeit/duckhu/config/QueryDslConfig.java
  src/main/java/com/codeit/duckhu/domain/user/controller/UserController.java
  src/main/java/com/codeit/duckhu/domain/user/controller/api/UserApi.java
  src/main/java/com/codeit/duckhu/domain/user/exception/EmailDuplicateException.java
  src/main/java/com/codeit/duckhu/domain/user/exception/ForbiddenDeleteException.java
  src/main/java/com/codeit/duckhu/domain/user/exception/ForbiddenUpdateException.java
  src/main/java/com/codeit/duckhu/domain/user/exception/InvalidLoginException.java
  src/main/java/com/codeit/duckhu/domain/user/exception/NotFoundUserException.java
  src/main/java/com/codeit/duckhu/domain/user/exception/UserErrorCode.java
  src/main/java/com/codeit/duckhu/domain/user/exception/UserErrorResponse.java
  src/main/java/com/codeit/duckhu/domain/user/exception/UserException.java
  src/main/java/com/codeit/duckhu/domain/user/exception/UserExceptionHandler.java
  src/main/java/com/codeit/duckhu/domain/user/service/UserServiceImpl.java
  src/main/java/com/codeit/duckhu/global/exception/ErrorCode.java
  src/main/java/com/codeit/duckhu/global/exception/GlobalExceptionHandler.java
  src/test/java/com/codeit/duckhu/domain/comments/CommentControllerTest.java
  src/test/java/com/codeit/duckhu/domain/comments/CommentServiceTest.java
  src/test/java/com/codeit/duckhu/domain/user/controller/UserControllerTest.java
  src/test/java/com/codeit/duckhu/domain/user/integration/UserTest.java
  src/test/java/com/codeit/duckhu/domain/user/repository/UserRepositoryTest.java
Labels: 🔨기능수리

#62 [🛠Refactor] 요청헤더로 로그인 인증 관리
  build.gradle
  src/main/java/com/codeit/duckhu/config/FilterConfig.java
  src/main/java/com/codeit/duckhu/domain/review/entity/Review.java
  src/main/java/com/codeit/duckhu/domain/review/repository/ReviewRepository.java
  src/main/java/com/codeit/duckhu/domain/review/service/ReviewService.java
  src/main/java/com/codeit/duckhu/domain/review/service/impl/ReviewServiceImpl.java
  src/main/java/com/codeit/duckhu/domain/user/UserAuthenticationFilter.java
  src/main/java/com/codeit/duckhu/domain/user/controller/UserController.java
  src/main/java/com/codeit/duckhu/domain/user/controller/api/UserApi.java
  src/main/java/com/codeit/duckhu/domain/user/entity/User.java
  src/main/java/com/codeit/duckhu/domain/user/service/UserServiceImpl.java
  src/test/java/com/codeit/duckhu/domain/book/repository/BookReviewTest.java
  src/test/java/com/codeit/duckhu/domain/review/repository/ReviewRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/user/controller/UserControllerTest.java
  src/test/java/com/codeit/duckhu/domain/user/integration/UserTest.java
  src/test/java/com/codeit/duckhu/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/user/service/UserServiceImplTest.java
Labels: 🔨기능수리

#73 Feat/63 ReviewController, ControllerTest
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/codeit/duckhu/domain/review/controller/ReviewController.java
  src/main/java/com/codeit/duckhu/domain/review/dto/ReviewSearchRequestDto.java
  src/main/java/com/codeit/duckhu/domain/review/service/impl/ReviewServiceImpl.java
  src/main/resources/.DS_Store
  src/test/java/com/codeit/duckhu/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/codeit/duckhu/domain/review/service/ReviewServiceTest.java
Labels: ✨기능, 👨🏻‍🏫테스트

#78 :lipstick: 정적 리소스 교체
  src/main/resources/static/assets/index-BBiuw4BK.js
  src/main/resources/static/assets/index-CngKKUej.js
  src/main/resources/static/index.html
Labels: 🔨기능수리

#76 [✨Feat] 파워유저 조회 기능
  src/main/java/com/codeit/duckhu/DuckhuApplication.java
  src/main/java/com/codeit/duckhu/config/FilterConfig.java
  src/main/java/com/codeit/duckhu/domain/review/dto/ReviewSearchRequestDto.java
  src/main/java/com/codeit/duckhu/domain/review/entity/LikedUserId.java
  src/main/java/com/codeit/duckhu/domain/review/service/impl/ReviewServiceImpl.java
  src/main/java/com/codeit/duckhu/domain/user/UserAuthenticationFilter.java
  src/main/java/com/codeit/duckhu/domain/user/dto/CursorPageResponsePowerUserDto.java
  src/main/java/com/codeit/duckhu/domain/user/dto/PowerUserDto.java
  src/main/java/com/codeit/duckhu/domain/user/dto/PowerUserStatsDto.java
  src/main/java/com/codeit/duckhu/domain/user/entity/PowerUser.java
  src/main/java/com/codeit/duckhu/domain/user/entity/User.java
  src/main/java/com/codeit/duckhu/domain/user/mapper/PowerUserMapper.java
  src/main/java/com/codeit/duckhu/domain/user/repository/poweruser/PowerUserRepository.java
  src/main/java/com/codeit/duckhu/domain/user/repository/poweruser/PowerUserRepositoryCustom.java
  src/main/java/com/codeit/duckhu/domain/user/repository/poweruser/PowerUserRepositoryImpl.java
  src/main/java/com/codeit/duckhu/domain/user/service/PowerUserBatchScheduler.java
  src/main/java/com/codeit/duckhu/domain/user/service/UserService.java
  src/main/java/com/codeit/duckhu/domain/user/service/UserServiceImpl.java
  src/test/java/com/codeit/duckhu/domain/user/service/UserServiceImplTest.java
Labels: ✨기능, 👨🏻‍🏫테스트

#80 Feat/74 ReviewController LikeReview 구현 및 테스트, 파라미터 userId 추가
  .gitignore
  src/main/java/com/codeit/duckhu/domain/review/controller/ReviewController.java
  src/main/java/com/codeit/duckhu/domain/review/dto/CursorPageResponseReviewDto.java
  src/main/java/com/codeit/duckhu/domain/review/entity/PopularReview.java
  src/main/java/com/codeit/duckhu/domain/review/entity/Review.java
  src/main/java/com/codeit/duckhu/domain/review/exception/ReviewErrorCode.java
  src/main/java/com/codeit/duckhu/domain/review/repository/popular/PopularReviewRepository.java
  src/main/java/com/codeit/duckhu/domain/review/service/ReviewService.java
  src/main/java/com/codeit/duckhu/domain/review/service/impl/ReviewServiceImpl.java
  src/test/java/com/codeit/duckhu/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/codeit/duckhu/domain/review/service/ReviewServiceTest.java
Labels: ✨기능, 🛠리팩토링, 👨🏻‍🏫테스트

#85 ✨ 인기 도서 배치 처리 작업
  src/main/java/com/codeit/duckhu/domain/book/dto/PopularBookScore.java
  src/main/java/com/codeit/duckhu/domain/book/repository/BookRepository.java
  src/main/java/com/codeit/duckhu/domain/book/repository/popular/PopularBookRepository.java
  src/main/java/com/codeit/duckhu/domain/book/service/PopularBookBatchScheduler.java
  src/main/java/com/codeit/duckhu/domain/book/service/PopularBookBatchService.java
  src/main/java/com/codeit/duckhu/domain/review/repository/ReviewRepository.java
Labels: ✨기능

#88 [🛠Refactor] 파워유저 조회 기능 컨트롤러 생성, 테스트 추가, 관련 문제 수정
  src/main/java/com/codeit/duckhu/domain/review/entity/Review.java
  src/main/java/com/codeit/duckhu/domain/user/UserAuthenticationFilter.java
  src/main/java/com/codeit/duckhu/domain/user/controller/UserController.java
  src/main/java/com/codeit/duckhu/domain/user/controller/api/UserApi.java
  src/main/java/com/codeit/duckhu/domain/user/dto/PowerUserStatsDto.java
  src/main/java/com/codeit/duckhu/domain/user/entity/User.java
  src/main/java/com/codeit/duckhu/domain/user/repository/poweruser/PowerUserRepository.java
  src/main/java/com/codeit/duckhu/domain/user/repository/poweruser/PowerUserRepositoryImpl.java
  src/main/java/com/codeit/duckhu/domain/user/service/UserServiceImpl.java
  src/test/java/com/codeit/duckhu/domain/user/controller/UserControllerTest.java
  src/test/java/com/codeit/duckhu/domain/user/integration/UserTest.java
  src/test/java/com/codeit/duckhu/domain/user/repository/PowerUserRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/user/service/UserServiceImplTest.java
  src/test/resources/application-test.yml
  src/test/resources/data.sql
Labels: 🐛버그, 🛠리팩토링, 👨🏻‍🏫테스트

#91 Feat/81 PopularReview 구현 및 배치작업
  src/main/java/com/codeit/duckhu/domain/comment/repository/CommentRepository.java
  src/main/java/com/codeit/duckhu/domain/review/controller/ReviewController.java
  src/main/java/com/codeit/duckhu/domain/review/dto/CursorPageResponsePopularReviewDto.java
  src/main/java/com/codeit/duckhu/domain/review/dto/PopularReviewDto.java
  src/main/java/com/codeit/duckhu/domain/review/dto/ReviewScore.java
  src/main/java/com/codeit/duckhu/domain/review/dto/ReviewSearchRequestDto.java
  src/main/java/com/codeit/duckhu/domain/review/entity/PopularReview.java
  src/main/java/com/codeit/duckhu/domain/review/repository/LikedUserIdRepository.java
  src/main/java/com/codeit/duckhu/domain/review/repository/PopularReviewRepository.java
  src/main/java/com/codeit/duckhu/domain/review/repository/ReviewRepository.java
  src/main/java/com/codeit/duckhu/domain/review/repository/custom/PopularReviewRepositoryCustom.java
  src/main/java/com/codeit/duckhu/domain/review/repository/custom/ReviewRepositoryCustom.java
  src/main/java/com/codeit/duckhu/domain/review/repository/custom/impl/PopularReviewRepositoryCustomImpl.java
  src/main/java/com/codeit/duckhu/domain/review/repository/custom/impl/ReviewRepositoryCustomImpl.java
  src/main/java/com/codeit/duckhu/domain/review/repository/popular/PopularReviewRepository.java
  src/main/java/com/codeit/duckhu/domain/review/service/ReviewService.java
  src/main/java/com/codeit/duckhu/domain/review/service/impl/PopularReviewBatchService.java
  src/main/java/com/codeit/duckhu/domain/review/service/impl/ReviewServiceImpl.java
  src/main/resources/schema.sql
  src/test/java/com/codeit/duckhu/domain/review/repository/ReviewRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/review/service/ReviewServiceTest.java
Labels: ✨기능, 🛠리팩토링

#93 [🛠Refactor] 사용자 로그 추가 & 파워유저 정렬(등수) 변경
  src/main/java/com/codeit/duckhu/domain/user/controller/UserController.java
  src/main/java/com/codeit/duckhu/domain/user/repository/poweruser/PowerUserRepositoryImpl.java
  src/main/java/com/codeit/duckhu/domain/user/service/PowerUserBatchScheduler.java
  src/main/java/com/codeit/duckhu/domain/user/service/UserServiceImpl.java
  src/test/resources/application-test.yml
Labels: 🐛버그, 🛠리팩토링

#98 ♻️ 도서 테스트 코드 수정
  src/main/java/com/codeit/duckhu/domain/book/naver/ImageConverter.java
  src/main/java/com/codeit/duckhu/domain/book/naver/ImageConverterImpl.java
  src/main/java/com/codeit/duckhu/domain/book/naver/NaverBookClient.java
  src/test/java/com/codeit/duckhu/domain/book/controller/BookControllerTest.java
  src/test/java/com/codeit/duckhu/domain/book/mapper/BookMapperTest.java
  src/test/java/com/codeit/duckhu/domain/book/naver/NaverBookClientIntegrationTest.java
  src/test/java/com/codeit/duckhu/domain/book/naver/NaverBookClientTest.java
  src/test/java/com/codeit/duckhu/domain/book/service/BookServiceImplTest.java
Labels: 👨🏻‍🏫테스트

#101 feat: 알림 등록 및 삭제 기능 스케쥴러 구현 #95
  src/main/java/com/codeit/duckhu/config/SchedulingConfig.java
  src/main/java/com/codeit/duckhu/domain/notification/entity/Notification.java
  src/main/java/com/codeit/duckhu/domain/notification/repository/NotificationRepository.java
  src/main/java/com/codeit/duckhu/domain/notification/service/NotificationService.java
  src/main/java/com/codeit/duckhu/domain/notification/service/impl/NotificationServiceImpl.java
  src/main/java/com/codeit/duckhu/domain/review/service/impl/PopularReviewBatchService.java
  src/test/java/com/codeit/duckhu/domain/notification/service/NotificationServiceTest.java
Labels: ✨기능, 👨🏻‍🏫테스트

#102 [🛠Refactor] 에러응답 구조 수정
  src/main/java/com/codeit/duckhu/domain/book/exception/BookException.java
  src/main/java/com/codeit/duckhu/domain/comment/exception/CommentException.java
  src/main/java/com/codeit/duckhu/domain/comment/exception/CommentExceptionHandler.java
  src/main/java/com/codeit/duckhu/domain/comment/exception/NoAuthorityException.java
  src/main/java/com/codeit/duckhu/domain/comment/exception/NoCommentException.java
  src/main/java/com/codeit/duckhu/domain/comment/exception/NoHeaderException.java
  src/main/java/com/codeit/duckhu/domain/comment/service/CommentService.java
  src/main/java/com/codeit/duckhu/domain/comment/service/ErrorCode.java
  src/main/java/com/codeit/duckhu/domain/notification/controller/NotificationController.java
  src/main/java/com/codeit/duckhu/domain/notification/exception/NotificationException.java
  src/main/java/com/codeit/duckhu/domain/notification/service/impl/NotificationServiceImpl.java
  src/main/java/com/codeit/duckhu/domain/review/controller/ReviewController.java
  src/main/java/com/codeit/duckhu/domain/user/UserAuthenticationFilter.java
  src/main/java/com/codeit/duckhu/domain/user/controller/UserController.java
  src/main/java/com/codeit/duckhu/domain/user/dto/UserUpdateRequest.java
  src/main/java/com/codeit/duckhu/domain/user/exception/EmailDuplicateException.java
  src/main/java/com/codeit/duckhu/domain/user/exception/ForbiddenDeleteException.java
  src/main/java/com/codeit/duckhu/domain/user/exception/ForbiddenUpdateException.java
  src/main/java/com/codeit/duckhu/domain/user/exception/InvalidLoginException.java
  src/main/java/com/codeit/duckhu/domain/user/exception/NotFoundUserException.java
  src/main/java/com/codeit/duckhu/domain/user/exception/UserException.java
  src/main/java/com/codeit/duckhu/domain/user/service/UserServiceImpl.java
  src/main/java/com/codeit/duckhu/global/exception/DomainException.java
  src/main/java/com/codeit/duckhu/global/exception/ErrorCode.java
  src/main/java/com/codeit/duckhu/global/exception/GlobalExceptionHandler.java
  src/main/java/com/codeit/duckhu/global/response/CustomApiResponse.java
  src/main/java/com/codeit/duckhu/global/response/ErrorResponse.java
  src/test/java/com/codeit/duckhu/domain/user/controller/UserControllerTest.java
  src/test/java/com/codeit/duckhu/domain/user/service/UserServiceImplTest.java
Labels: 🛠리팩토링

#108 [🐛Bug]회원가입 후 도서,리뷰,알림,댓글 데이터 불러오지 못하는 버그 해결
  src/main/java/com/codeit/duckhu/domain/user/UserAuthenticationFilter.java
  src/main/java/com/codeit/duckhu/domain/user/controller/UserController.java
  src/main/java/com/codeit/duckhu/domain/user/controller/api/UserApi.java
  src/main/java/com/codeit/duckhu/domain/user/service/UserServiceImpl.java
  src/main/java/com/codeit/duckhu/global/response/ErrorResponse.java
Labels: 🐛버그

#105 Ref/104 ReviewService 리팩토링 및 에러 코드 병합
  src/main/java/com/codeit/duckhu/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/codeit/duckhu/domain/comment/repository/CommentRepository.java
  src/main/java/com/codeit/duckhu/domain/comment/service/CommentService.java
  src/main/java/com/codeit/duckhu/domain/notification/service/impl/NotificationServiceImpl.java
  src/main/java/com/codeit/duckhu/domain/review/controller/ReviewController.java
  src/main/java/com/codeit/duckhu/domain/review/dto/ReviewCreateRequest.java
  src/main/java/com/codeit/duckhu/domain/review/entity/Review.java
  src/main/java/com/codeit/duckhu/domain/review/exception/ReviewCustomException.java
  src/main/java/com/codeit/duckhu/domain/review/exception/ReviewErrorCode.java
  src/main/java/com/codeit/duckhu/domain/review/service/impl/ReviewServiceImpl.java
  src/main/java/com/codeit/duckhu/global/exception/ErrorCode.java
  src/test/java/com/codeit/duckhu/domain/review/service/ReviewServiceTest.java
Labels: 🛠리팩토링

#119 Feat/116 LoggerBack 및 MDC 설정 추가
  .gitignore
  src/main/java/com/codeit/duckhu/global/logging/LoggingFilter.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: ✨기능

#124 [🐛Bug]amazoncoretto-alpine과 tess4j충돌해결
  .gitignore
  Dockerfile
Labels: 🐛버그

#125 [🛠Refactor]사용자 테스트코드 리팩토링
  build.gradle
  src/main/java/com/codeit/duckhu/domain/user/controller/UserController.java
  src/test/java/com/codeit/duckhu/domain/user/controller/UserControllerTest.java
  src/test/java/com/codeit/duckhu/domain/user/integration/UserTest.java
  src/test/java/com/codeit/duckhu/domain/user/repository/PowerUserRepositoryTest.java
Labels: 🛠리팩토링, 👨🏻‍🏫테스트

#126 112 refactor 알림 테스트 코드 리팩토링
  build.gradle
  src/main/java/com/codeit/duckhu/domain/notification/repository/NotificationRepository.java
  src/main/java/com/codeit/duckhu/domain/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/codeit/duckhu/domain/notification/repository/NotificationRepositoryImpl.java
  src/test/java/com/codeit/duckhu/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/codeit/duckhu/domain/notification/repository/NotificationRepositoryTest.java
Labels: 🔨기능수리, 👨🏻‍🏫테스트

#131 Test/120 Review test코드 추가 및 수정
  build.gradle
  src/main/java/com/codeit/duckhu/domain/review/repository/LikedUserIdRepository.java
  src/test/java/com/codeit/duckhu/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/codeit/duckhu/domain/review/repository/PopularReviewRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/review/repository/ReviewRepositoryTest.java
  src/test/java/com/codeit/duckhu/domain/review/service/ReviewServiceTest.java
Labels: 👨🏻‍🏫테스트

#129 🚀 CI/CD 파이프라인 구축하기
  .github/workflows/cicd.yml
  Dockerfile
  ecs/task-definition.json
Labels: 🚀 배포

#138 :bug: 릴리즈 브랜치 생성 수정 완료
  .github/workflows/cicd.yml
Labels: 🐛버그

#145 :recycle: release 브랜치를 제외시킴
  .github/workflows/cicd.yml
Labels: 🛠리팩토링
